name: CI Workflows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  static-checks:
    name: Static Checks
    uses: ./.github/workflows/run-static-checks.yml

  test:
    name: Test
    uses: ./.github/workflows/run-tests.yml

  coverage:
    name: Coverage
    uses: ./.github/workflows/collect-coverage.yml

  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml